"""initial run

Revision ID: 8e1e6ae784ec
Revises: 
Create Date: 2024-09-18 19:02:36.282558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1e6ae784ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_publisher', sa.String(), nullable=False),
    sa.Column('book_category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_book_category'), 'books', ['book_category'], unique=False)
    op.create_index(op.f('ix_books_book_publisher'), 'books', ['book_publisher'], unique=False)
    op.create_table('user',
    sa.Column('firstname', sa.String(length=30), nullable=False),
    sa.Column('lastname', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(), nullable=False, unique=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index(op.f('ix_books_book_publisher'), table_name='books')
    op.drop_index(op.f('ix_books_book_category'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
