FROM python:3.12.6-alpine3.20

WORKDIR /library-api

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

RUN alembic upgrade head

CMD [ "flask", "run", "--host=0.0.0.0", "--port=5050" ]