"""initial run

Revision ID: 211d44797498
Revises: 
Create Date: 2024-09-20 02:55:03.880463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211d44797498'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_publisher', sa.String(), nullable=False),
    sa.Column('book_category', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ON_SHELF', 'BORROWED', name='bookstatusenum'), nullable=False),
    sa.Column('book_title', sa.String(), nullable=False),
    sa.Column('curr_due_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_book_category'), 'books', ['book_category'], unique=False)
    op.create_index(op.f('ix_books_book_publisher'), 'books', ['book_publisher'], unique=False)
    op.create_index(op.f('ix_books_book_title'), 'books', ['book_title'], unique=True)
    op.create_table('user',
    sa.Column('firstname', sa.String(length=30), nullable=False),
    sa.Column('lastname', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('borrows',
    sa.Column('no_of_days', sa.Integer(), nullable=False),
    sa.Column('date_returned', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrows')
    op.drop_table('user')
    op.drop_index(op.f('ix_books_book_title'), table_name='books')
    op.drop_index(op.f('ix_books_book_publisher'), table_name='books')
    op.drop_index(op.f('ix_books_book_category'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
